### ISSUE TITLE
Firefox headless in GebConfig does not work

### ISSUE THREAD

**Issue by GuopingJia** [BCDevOps/BDDStack#7]
With the same setup in GebConfig for firefoxHeadless, it does not work !

o.addArguments("-headless")

We are running Selenium 3.11.0, geckoDriver 0.21.0 with firefox 61.0.1 (64 bits). All tests failed with CreateWebDriverException.

The normal firefox setup works well.

**Comment by GuopingJia** [comment]
Some other test respo recommends using "--headless". Not sure which one is correct.

Tried this anyway, did not work either.

**Comment by ShellyXueHan** [comment]
Hi there,

sorry for the late reply. Is the error still existing? I am not able to reproduce it, so could you provide error logs if needed?

Thanks!

**Comment by GuopingJia** [comment]
Thank you for your reply. 

The issue has been fixed in my environment. That's mainly due to the geckcodriver setup and some additional configuration for company proxy. Everthing is working now.

Btw,  below is what I  am using in GebConfig for firefox headless:

options.addArguments('--headless');
